### ISSUE TITLE
gentoopmq: AttributeError: 'Namespace' object has no attribute 'instance'

### ISSUE THREAD

**Issue by thesamesam** [projg2/gentoopm#3]
```console
$ gentoopmq
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/gentoopmq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/gentoopm/querycli.py", line 291, in main
    sys.exit(cli.main(sys.argv))
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gentoopm/querycli.py", line 286, in main
    return args.instance(pm, args) or 0
           ^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'instance'
```

I get the same with py3.10/11.

**Comment by mgorny** [comment]
Right, one day I need to fix that. You need to pass a subcommand.
